-- ============================================================
-- ECOM_ANALYTICS Infrastructure Setup
-- ============================================================

-- Create database
CREATE DATABASE IF NOT EXISTS ECOM_ANALYTICS;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.MARTS;
CREATE SCHEMA IF NOT EXISTS ECOM_ANALYTICS.METRICS;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS ECOM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
