-- ============================================================
-- ECOM_ANALYTICS.RAW - Raw Source Tables
-- ============================================================

USE DATABASE ECOM_ANALYTICS;
USE SCHEMA RAW;

-- Customers
CREATE TABLE IF NOT EXISTS RAW_CUSTOMERS (
  CUSTOMER_ID INTEGER,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  EMAIL VARCHAR,
  SIGNUP_DATE DATE,
  COUNTRY VARCHAR,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Products
CREATE TABLE IF NOT EXISTS RAW_PRODUCTS (
  PRODUCT_ID INTEGER,
  PRODUCT_NAME VARCHAR,
  CATEGORY VARCHAR,
  PRICE NUMBER(10,2),
  SUPPLIER VARCHAR,
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Orders
CREATE TABLE IF NOT EXISTS RAW_ORDERS (
  ORDER_ID INTEGER,
  CUSTOMER_ID INTEGER,
  ORDER_DATE TIMESTAMP_NTZ,
  STATUS VARCHAR,
  TOTAL_AMOUNT NUMBER(12,2),
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Order Items
CREATE TABLE IF NOT EXISTS RAW_ORDER_ITEMS (
  ORDER_ITEM_ID INTEGER,
  ORDER_ID INTEGER,
  PRODUCT_ID INTEGER,
  QUANTITY INTEGER,
  UNIT_PRICE NUMBER(10,2),
  _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
