-- ============================================================
-- ECOM_ANALYTICS.RAW - Streams for Change Data Capture
-- ============================================================

USE DATABASE ECOM_ANALYTICS;
USE SCHEMA RAW;

-- Stream on RAW_ORDERS
CREATE OR REPLACE STREAM RAW_ORDERS_STREAM
  ON TABLE RAW_ORDERS
  SHOW_INITIAL_ROWS = TRUE;

-- Stream on RAW_ORDER_ITEMS
CREATE OR REPLACE STREAM RAW_ORDER_ITEMS_STREAM
  ON TABLE RAW_ORDER_ITEMS
  SHOW_INITIAL_ROWS = TRUE;

-- Stream on RAW_CUSTOMERS
CREATE OR REPLACE STREAM RAW_CUSTOMERS_STREAM
  ON TABLE RAW_CUSTOMERS
  SHOW_INITIAL_ROWS = TRUE;
